const imagePath = {
  carAvanza: './images/avanza.jpg',
  carAyla: './images/ayla.jpg',
  carCalya: './images/calya.jpg',
  carPajero: './images/pajero.jpg',
  carXenia: './images/xenia.jpg',
  carXpander: './images/xpander.jpg',
  consumenOne: './images/consumen_1.png',
  consumenTwo: './images/consumen_2.png',
  hero: './images/hero.png',
  iconAvatar: './icons/avatar.png',
  iconComplete: './icons/icon_complete.png',
  iconEmail: './icons/icon_mail.png',
  iconFacebook: './icons/icon_facebook.png',
  iconInstagram: './icons/icon_instagram.png',
  iconPrice: './icons/icon_price.png',
  iconProfessional: './icons/icon_professional.png',
  iconTime: './icons/icon_24hrs.png',
  iconTwitch: './icons/icon_twitch.png',
  iconTwitter: './icons/icon_twitter.png',
  logo: './images/logo.png',
  signIn: './images/sign-in.png',
  services: './images/services.png',
}

export default imagePath